/* 词汇数据 — 改编自《怎样学习英语词汇》(董石祥编, 1978)
   方法框架沿用原书；例词已现代化：剔除时代政治口号、修正扫描错字、补充常用词。
   字段约定：a=词缀 g=语义组 mc=中文义 me=英文义 ex=[base,基础义,derived,派生义] */
window.VOCAB = {

/* ===================== 前缀 ===================== */
prefixes: [
 {a:"un-", g:"否定", mc:"不；非；相反", me:"not / reverse", ex:[
   ["happy","快乐的","unhappy","不快乐的"],["able","能的","unable","不能的"],
   ["fair","公平的","unfair","不公平的"],["safe","安全的","unsafe","不安全的"],
   ["known","已知的","unknown","未知的"],["lock","锁","unlock","开锁"],
   ["tie","打结","untie","解开"],["load","装载","unload","卸下"]],
   note:"加在动词上时表示“取消、相反”的动作（unlock 开锁、undo 撤销）。"},
 {a:"in-", g:"否定", mc:"不；无", me:"not", ex:[
   ["correct","正确的","incorrect","不正确的"],["complete","完整的","incomplete","不完整的"],
   ["dependent","依赖的","independent","独立的"],["formal","正式的","informal","非正式的"],
   ["visible","可见的","invisible","看不见的"],["direct","直接的","indirect","间接的"]],
   note:"源自拉丁语，随后面字母同化：l 前→il-，r 前→ir-，m/b/p 前→im-。"},
 {a:"il-", g:"否定", mc:"不（l 前）", me:"not (before l)", ex:[
   ["legal","合法的","illegal","非法的"],["logical","合逻辑的","illogical","不合逻辑的"]]},
 {a:"ir-", g:"否定", mc:"不（r 前）", me:"not (before r)", ex:[
   ["regular","规则的","irregular","不规则的"],["responsible","负责的","irresponsible","不负责的"]]},
 {a:"im-", g:"否定", mc:"不（m/b/p 前）", me:"not (before m,b,p)", ex:[
   ["possible","可能的","impossible","不可能的"],["polite","礼貌的","impolite","无礼的"],
   ["patient","有耐心的","impatient","不耐烦的"],["perfect","完美的","imperfect","不完美的"]]},
 {a:"dis-", g:"否定", mc:"不；取消；分开", me:"not / un-", ex:[
   ["like","喜欢","dislike","厌恶"],["agree","同意","disagree","不同意"],
   ["appear","出现","disappear","消失"],["honest","诚实的","dishonest","不诚实的"],
   ["cover","遮盖","discover","发现"],["order","秩序","disorder","混乱"],
   ["connect","连接","disconnect","断开"]]},
 {a:"non-", g:"否定", mc:"非；不", me:"non-", ex:[
   ["sense","意义","nonsense","废话"],["stop","停","nonstop","直达的"],
   ["smoker","吸烟者","non-smoker","不吸烟者"],["fiction","小说","nonfiction","纪实文学"],
   ["profit","利润","non-profit","非营利的"]]},
 {a:"mis-", g:"否定", mc:"误；坏", me:"wrongly", ex:[
   ["take","拿","mistake","错误"],["understand","理解","misunderstand","误解"],
   ["use","使用","misuse","滥用"],["lead","引导","mislead","误导"],
   ["print","印刷","misprint","印刷错误"],["spell","拼写","misspell","拼错"]]},
 {a:"de-", g:"反向", mc:"向下；除去；反向", me:"down / reverse", ex:[
   ["crease","增加","decrease","减少"],["frost","霜","defrost","解冻"],
   ["value","价值","devalue","贬值"],["code","编码","decode","解码"],
   ["form","形状","deform","使变形"]]},
 {a:"anti-", g:"反向", mc:"反；抗", me:"against", ex:[
   ["war","战争","antiwar","反战的"],["body","身体","antibody","抗体"],
   ["freeze","结冰","antifreeze","防冻剂"],["social","社交的","antisocial","反社会的"],
   ["virus","病毒","antivirus","杀毒的"]]},
 {a:"counter-", g:"反向", mc:"反；对应", me:"counter / opposite", ex:[
   ["attack","攻击","counterattack","反攻"],["part","部分","counterpart","对应物"],
   ["act","行动","counteract","抵消"]]},
 {a:"re-", g:"重复", mc:"再；重新；回", me:"again / back", ex:[
   ["build","建造","rebuild","重建"],["write","写","rewrite","重写"],
   ["use","使用","reuse","重新使用"],["cycle","循环","recycle","回收"],
   ["turn","转","return","返回"],["view","看","review","复习"],
   ["play","播放","replay","重播"]]},
 {a:"en- / em-", g:"使役", mc:"使成为；使进入", me:"make / put into", ex:[
   ["large","大的","enlarge","扩大"],["rich","富的","enrich","使丰富"],
   ["able","能的","enable","使能够"],["force","力量","enforce","强制执行"],
   ["courage","勇气","encourage","鼓励"],["danger","危险","endanger","危及"],
   ["joy","欢乐","enjoy","享受"],["power","权力","empower","授权"]],
   note:"在 b、p、m 前写作 em-（embrace 拥抱、empower 授权）。"},
 {a:"pre-", g:"时序", mc:"先于；预先", me:"before", ex:[
   ["view","看","preview","预览"],["pay","付款","prepay","预付"],
   ["school","学校","preschool","学前的"],["historic","历史的","prehistoric","史前的"],
   ["heat","加热","preheat","预热"]]},
 {a:"post-", g:"时序", mc:"后于；在后", me:"after", ex:[
   ["war","战争","postwar","战后的"],["pone","（无）","postpone","推迟"],
   ["graduate","毕业生","postgraduate","研究生"],["script","文字","postscript","附言(P.S.)"]]},
 {a:"fore-", g:"时序", mc:"前；预", me:"before / front", ex:[
   ["cast","投","forecast","预报"],["see","看见","foresee","预见"],
   ["head","头","forehead","前额"],["word","词","foreword","前言"],
   ["tell","说","foretell","预言"]]},
 {a:"ex-", g:"时序", mc:"前任；向外", me:"former / out", ex:[
   ["president","总统","ex-president","前总统"],["wife","妻子","ex-wife","前妻"],
   ["port","（运）","export","出口"],["pand","（无）","expand","扩张"],
   ["it","（无）","exit","出口"]]},
 {a:"inter-", g:"方位", mc:"在……之间；相互", me:"between / among", ex:[
   ["national","国家的","international","国际的"],["act","行动","interact","互动"],
   ["net","网","internet","互联网"],["view","看","interview","面试"],
   ["change","改变","interchange","互换"],["section","部分","intersection","交叉口"]]},
 {a:"sub-", g:"方位", mc:"在下；次于", me:"under / sub-", ex:[
   ["way","路","subway","地铁"],["marine","海的","submarine","潜艇"],
   ["title","标题","subtitle","字幕"],["divide","分","subdivide","细分"],
   ["standard","标准","substandard","不合标准的"],["set","集合","subset","子集"]]},
 {a:"super-", g:"方位", mc:"超；上；过", me:"above / beyond", ex:[
   ["market","市场","supermarket","超市"],["man","人","superman","超人"],
   ["vise","看","supervise","监督"],["power","力量","superpower","超级大国"],
   ["star","星","superstar","superstar 巨星"],["natural","自然的","supernatural","超自然的"]]},
 {a:"sur-", g:"方位", mc:"在上；超过", me:"over / above", ex:[
   ["face","脸/面","surface","表面"],["plus","加","surplus","盈余"],
   ["pass","通过","surpass","超过"],["name","名字","surname","姓"],
   ["round","圆/周","surround","包围"]]},
 {a:"over-", g:"方位", mc:"过度；在上", me:"over / too much", ex:[
   ["eat","吃","overeat","吃得过多"],["work","工作","overwork","过度劳累"],
   ["come","来","overcome","克服"],["flow","流","overflow","溢出"],
   ["look","看","overlook","忽视"],["coat","外套","overcoat","大衣"]]},
 {a:"under-", g:"方位", mc:"在下；不足", me:"below / not enough", ex:[
   ["ground","地面","underground","地下的"],["line","线","underline","划线强调"],
   ["water","水","underwater","水下的"],["stand","站","understand","理解"],
   ["wear","穿","underwear","内衣"],["estimate","估计","underestimate","低估"]]},
 {a:"trans-", g:"方位", mc:"跨越；转换", me:"across / change", ex:[
   ["port","（运）","transport","运输"],["form","形状","transform","改造"],
   ["late","（无）","translate","翻译"],["fer","（带）","transfer","转移"],
   ["plant","种植","transplant","移植"],["mit","（送）","transmit","传输"]]},
 {a:"co- / com- / con-", g:"方位", mc:"共同；一起", me:"together / with", ex:[
   ["operate","操作","cooperate","合作"],["exist","存在","coexist","共存"],
   ["worker","工人","coworker","同事"],["bine","（无）","combine","结合"],
   ["nect","（无）","connect","连接"],["tact","（触）","contact","联系"]]},
 {a:"semi-", g:"数量", mc:"一半", me:"half", ex:[
   ["circle","圆","semicircle","半圆"],["final","决赛","semifinal","半决赛"],
   ["conductor","导体","semiconductor","半导体"],["colon","冒号","semicolon","分号"]]},
 {a:"tele-", g:"数量", mc:"远", me:"far / distant", ex:[
   ["phone","声音","telephone","电话"],["scope","镜","telescope","望远镜"],
   ["vision","视","television","电视"],["graph","写","telegraph","电报"]]},
 {a:"mid-", g:"数量", mc:"中间", me:"middle", ex:[
   ["night","夜","midnight","午夜"],["day","天","midday","正午"],
   ["way","路","midway","中途"],["summer","夏","midsummer","仲夏"]]},
 {a:"vice-", g:"数量", mc:"副", me:"deputy", ex:[
   ["president","总统/会长","vice-president","副总统/副会长"],
   ["chairman","主席","vice-chairman","副主席"],["principal","校长","vice-principal","副校长"]]},
 {a:"kilo-", g:"数量", mc:"千", me:"thousand", ex:[
   ["metre","米","kilometre","千米"],["gram","克","kilogram","千克"],["watt","瓦","kilowatt","千瓦"]]}
],

/* ===================== 后缀 ===================== */
suffixes: [
 {a:"-er", cat:"名词·表人", mc:"做……的人", me:"one who does", form:"动词 + er", ex:[
   ["teach","教","teacher","教师"],["work","工作","worker","工人"],
   ["write","写","writer","作家"],["read","读","reader","读者"],
   ["sing","唱","singer","歌手"],["lead","领导","leader","领导者"],
   ["play","玩/演奏","player","运动员/演奏者"]]},
 {a:"-or", cat:"名词·表人", mc:"做……的人", me:"one who does", form:"动词 + or", ex:[
   ["act","表演","actor","演员"],["sail","航行","sailor","水手"],
   ["visit","访问","visitor","访客"],["direct","指导","director","导演"],
   ["invent","发明","inventor","发明家"],["edit","编辑","editor","编辑"]]},
 {a:"-ist", cat:"名词·表人", mc:"……者；专家", me:"one who / -ist", form:"名词 + ist", ex:[
   ["art","艺术","artist","艺术家"],["science(sci)","科学","scientist","科学家"],
   ["piano","钢琴","pianist","钢琴家"],["tour","旅游","tourist","游客"],
   ["journal","期刊","journalist","记者"],["novel","小说","novelist","小说家"]],
   note:"原书将 physist 误印；正确为 physicist（物理学家）。"},
 {a:"-ian", cat:"名词·表人", mc:"……家；……人", me:"specialist in", form:"名词 + ian", ex:[
   ["music","音乐","musician","音乐家"],["history","历史","historian","历史学家"],
   ["library","图书馆","librarian","图书管理员"],["magic","魔术","magician","魔术师"],
   ["politics","政治","politician","政治家"],["electric","电","electrician","电工"]]},
 {a:"-ee", cat:"名词·表人", mc:"受……者", me:"one who is …ed", form:"动词 + ee", ex:[
   ["employ","雇用","employee","雇员"],["train","培训","trainee","受训者"],
   ["interview","面试","interviewee","受访者"],["refuge","庇护","refugee","难民"]]},
 {a:"-ese", cat:"名词·表人", mc:"……人；……语", me:"of a country", form:"国名/地名 + ese", ex:[
   ["China","中国","Chinese","中国人；汉语"],["Japan","日本","Japanese","日本人；日语"],
   ["Vietnam","越南","Vietnamese","越南人；越南语"],["Portug","葡萄牙","Portuguese","葡萄牙人；葡语"]]},
 {a:"-ness", cat:"名词·抽象", mc:"性质；状态", me:"quality / state", form:"形容词 + ness", ex:[
   ["kind","和善的","kindness","和善"],["happy","快乐的","happiness","幸福"],
   ["dark","黑暗的","darkness","黑暗"],["ill","病的","illness","疾病"],
   ["weak","弱的","weakness","弱点"],["sad","悲伤的","sadness","悲伤"]]},
 {a:"-ity", cat:"名词·抽象", mc:"性质；状态", me:"quality / state", form:"形容词 + ity", ex:[
   ["able","能的","ability","能力"],["active","活跃的","activity","活动"],
   ["equal","平等的","equality","平等"],["real","真实的","reality","现实"],
   ["possible","可能的","possibility","可能性"],["pure","纯的","purity","纯度"]]},
 {a:"-tion / -ation", cat:"名词·抽象", mc:"动作；结果", me:"action / result", form:"动词 + (a)tion", ex:[
   ["act","行动","action","行动"],["educate","教育","education","教育"],
   ["inform","通知","information","信息"],["invent","发明","invention","发明"],
   ["pronounce","发音","pronunciation","发音"],["produce","生产","production","生产"]]},
 {a:"-sion", cat:"名词·抽象", mc:"动作；状态", me:"action / state", form:"动词 + sion", ex:[
   ["decide","决定","decision","决定"],["discuss","讨论","discussion","讨论"],
   ["express","表达","expression","表达"],["expand","扩张","expansion","扩张"],
   ["revise","修订","revision","修订"]]},
 {a:"-ment", cat:"名词·抽象", mc:"行为；结果", me:"act / result", form:"动词 + ment", ex:[
   ["move","移动","movement","运动"],["govern","统治","government","政府"],
   ["develop","发展","development","发展"],["agree","同意","agreement","协议"],
   ["achieve","达成","achievement","成就"],["pay","支付","payment","付款"]]},
 {a:"-ance / -ence", cat:"名词·抽象", mc:"性质；状态", me:"quality / state", form:"动/形 + ance/ence", ex:[
   ["important","重要的","importance","重要性"],["distant","远的","distance","距离"],
   ["different","不同的","difference","差异"],["perform","表演","performance","表演"],
   ["appear","出现","appearance","外貌"],["experi","（无）","experience","经验"]]},
 {a:"-ship", cat:"名词·抽象", mc:"身份；关系", me:"state / relation", form:"名词 + ship", ex:[
   ["friend","朋友","friendship","友谊"],["leader","领袖","leadership","领导力"],
   ["member","成员","membership","会籍"],["partner","伙伴","partnership","合作关系"],
   ["relation","关系","relationship","关系"]],
   note:"原书 comradeship（同志爱）属时代用语，已替换为 membership/partnership。"},
 {a:"-hood", cat:"名词·抽象", mc:"时期；身份", me:"period / status", form:"名词 + hood", ex:[
   ["child","孩子","childhood","童年"],["neighbor","邻居","neighborhood","街区"],
   ["mother","母亲","motherhood","母亲身份"],["brother","兄弟","brotherhood","手足情"],
   ["live(li)","生活","livelihood","生计"]],
   note:"原书印作 livehood，正确为 livelihood。"},
 {a:"-dom", cat:"名词·抽象", mc:"领域；状态", me:"domain / state", form:"名/形 + dom", ex:[
   ["free","自由的","freedom","自由"],["king","国王","kingdom","王国"],
   ["wise","明智的","wisdom","智慧"],["bore","厌烦","boredom","无聊"]]},
 {a:"-ism", cat:"名词·抽象", mc:"主义；行为", me:"-ism / doctrine", form:"名/形 + ism", ex:[
   ["tour","旅游","tourism","旅游业"],["critic","批评","criticism","批评"],
   ["journal","期刊","journalism","新闻业"],["optim","乐观","optimism","乐观主义"],
   ["social","社会的","socialism","社会主义"],["capital","资本","capitalism","资本主义"]]},
 {a:"-th", cat:"名词·抽象", mc:"性质；状态", me:"quality / state", form:"形/动 + th", ex:[
   ["true","真的","truth","真理"],["grow","生长","growth","成长"],
   ["deep","深的","depth","深度"],["warm","暖的","warmth","温暖"],
   ["strong","强的","strength","力量"],["wide","宽的","width","宽度"]]},
 {a:"-ure", cat:"名词·抽象", mc:"动作；结果", me:"act / result", form:"动词 + ure", ex:[
   ["please","使高兴","pleasure","愉快"],["press","压","pressure","压力"],
   ["fail","失败","failure","失败"],["mix","混合","mixture","混合物"]]},
 {a:"-age", cat:"名词·抽象", mc:"总称；行为；费用", me:"collection / action / fee", form:"名/动 + age", ex:[
   ["village(vill)","村","village","村庄"],["pack","打包","package","包裹"],
   ["post","邮","postage","邮资"],["marry","结婚","marriage","婚姻"],
   ["short","短缺","shortage","短缺"],["store","储存","storage","储存"]]},
 {a:"-ful", cat:"形容词", mc:"充满……的", me:"full of", form:"名词 + ful", ex:[
   ["beauty","美","beautiful","美丽的"],["care","小心","careful","仔细的"],
   ["help","帮助","helpful","有帮助的"],["use","用","useful","有用的"],
   ["power","力量","powerful","强大的"],["success","成功","successful","成功的"]]},
 {a:"-less", cat:"形容词", mc:"无……的", me:"without", form:"名词 + less", ex:[
   ["care","小心","careless","粗心的"],["use","用","useless","无用的"],
   ["hope","希望","hopeless","绝望的"],["home","家","homeless","无家可归的"],
   ["end","尽头","endless","无尽的"],["harm","伤害","harmless","无害的"]]},
 {a:"-able / -ible", cat:"形容词", mc:"能……的；可……的", me:"able to be …ed", form:"动词 + able", ex:[
   ["read","读","readable","易读的"],["comfort","舒适","comfortable","舒适的"],
   ["rely","依靠","reliable","可靠的"],["enjoy","享受","enjoyable","愉快的"],
   ["vis","看","visible","可见的"],["flex","弯曲","flexible","灵活的"]]},
 {a:"-ous", cat:"形容词", mc:"有……的；多……的", me:"full of / having", form:"名词 + ous", ex:[
   ["fame","名声","famous","著名的"],["danger","危险","dangerous","危险的"],
   ["nerve","神经","nervous","紧张的"],["vary","变化","various","各种各样的"],
   ["poison","毒","poisonous","有毒的"],["mountain","山","mountainous","多山的"]]},
 {a:"-al", cat:"形容词", mc:"……的；与……有关的", me:"relating to", form:"名词 + al", ex:[
   ["nation","国家","national","国家的"],["nature","自然","natural","自然的"],
   ["culture","文化","cultural","文化的"],["music","音乐","musical","音乐的"],
   ["person","人","personal","个人的"],["centre","中心","central","中心的"]]},
 {a:"-ic", cat:"形容词", mc:"……的；……性的", me:"relating to", form:"名词 + ic", ex:[
   ["base","基础","basic","基本的"],["hero","英雄","heroic","英勇的"],
   ["science(sci)","科学","scientific","科学的"],["history(histor)","历史","historic","历史性的"],
   ["economy(econom)","经济","economic","经济的"],["atom","原子","atomic","原子的"]]},
 {a:"-ive", cat:"形容词", mc:"有……倾向的", me:"tending to", form:"动词 + ive", ex:[
   ["act","行动","active","积极的"],["create","创造","creative","有创造力的"],
   ["attract","吸引","attractive","有吸引力的"],["expense","花费","expensive","昂贵的"],
   ["effect","效果","effective","有效的"],["produce(product)","生产","productive","多产的"]]},
 {a:"-y", cat:"形容词", mc:"多……的；有……的", me:"characterized by", form:"名词 + y", ex:[
   ["rain","雨","rainy","下雨的"],["sun","太阳","sunny","晴朗的"],
   ["cloud","云","cloudy","多云的"],["wind","风","windy","有风的"],
   ["health","健康","healthy","健康的"],["luck","运气","lucky","幸运的"]]},
 {a:"-ish", cat:"形容词", mc:"有点……的；……的", me:"somewhat / of origin", form:"名/形 + ish", ex:[
   ["child","孩子","childish","幼稚的"],["fool","傻瓜","foolish","愚蠢的"],
   ["self","自己","selfish","自私的"],["red","红","reddish","微红的"],
   ["Eng(land)","英格兰","English","英国的"],["Span","西班牙","Spanish","西班牙的"]]},
 {a:"-en", cat:"动词", mc:"使变得……", me:"to make", form:"形容词 + en", ex:[
   ["wide","宽的","widen","加宽"],["deep","深的","deepen","加深"],
   ["strength","力量","strengthen","加强"],["short","短的","shorten","缩短"],
   ["bright","亮的","brighten","使明亮"],["weak","弱的","weaken","削弱"]]},
 {a:"-ify", cat:"动词", mc:"使……化", me:"to make", form:"名/形 + ify", ex:[
   ["simple","简单的","simplify","简化"],["beauty","美","beautify","美化"],
   ["class","类","classify","分类"],["pure","纯的","purify","净化"],
   ["clear","清楚的","clarify","澄清"],["ident","同一","identify","辨认"]]},
 {a:"-ize / -ise", cat:"动词", mc:"使……化", me:"to make", form:"名/形 + ize", ex:[
   ["modern","现代的","modernize","现代化"],["real","真实的","realize","实现"],
   ["organ","组织","organize","组织"],["memory(memor)","记忆","memorize","记住"],
   ["critic","批评","criticize","批评"],["industrial","工业的","industrialize","工业化"]]},
 {a:"-ate", cat:"动词", mc:"使……；做……", me:"to make / do", form:"名/形 + ate", ex:[
   ["active(activ)","活跃","activate","激活"],["educate(educ)","教育","educate","教育"],
   ["separate(separ)","分开","separate","分开"],["celebrate(celebr)","庆祝","celebrate","庆祝"],
   ["communicate(communic)","沟通","communicate","沟通"]]},
 {a:"-ly", cat:"副词", mc:"……地", me:"in a … manner", form:"形容词 + ly", ex:[
   ["quick","快的","quickly","快地"],["slow","慢的","slowly","慢地"],
   ["care(ful)","小心的","carefully","仔细地"],["happy","快乐的","happily","快乐地"],
   ["easy","容易的","easily","容易地"],["sudden","突然的","suddenly","突然地"]],
   note:"注意：friendly、lovely、weekly 是“名词+ly”构成的形容词，不是副词。"},
 {a:"-ward(s)", cat:"副词", mc:"朝……方向", me:"in the direction of", form:"介/名 + ward", ex:[
   ["for","前","forward(s)","向前"],["back","后","backward(s)","向后"],
   ["up","上","upward(s)","向上"],["east","东","eastward(s)","向东"]]}
],

/* ===================== 其他构词法 ===================== */
formation: {
 compound: { title:"合成法 Compounding",
   def:"由两个或两个以上的词组合成一个新词；多数意义可从字面看出。",
   groups:[
     {label:"名词 + 名词", items:[["classroom","教室"],["notebook","笔记本"],["basketball","篮球"],["raincoat","雨衣"],["toothbrush","牙刷"],["bedroom","卧室"],["sunflower","向日葵"],["football","足球"]]},
     {label:"形容词 + 名词", items:[["blackboard","黑板"],["highway","公路"],["greenhouse","温室"],["software","软件"],["smartphone","智能手机"],["midnight","午夜"]]},
     {label:"动词/副词 + 名词", items:[["pickpocket","扒手"],["overcoat","大衣"],["income","收入"],["outlook","展望"],["breakwater","防波堤"]]},
     {label:"名词 + 形容词", items:[["snow-white","雪白的"],["world-wide","全球的"],["homesick","想家的"],["waterproof","防水的"],["carefree","无忧无虑的"]]},
     {label:"名/形 + 名词-ed", items:[["kind-hearted","好心的"],["blue-eyed","蓝眼睛的"],["left-handed","左撇子的"],["old-fashioned","过时的"],["well-known","著名的"]]},
     {label:"名词 + 动名词", items:[["handwriting","笔迹"],["sightseeing","观光"],["shoemaking","制鞋"]]}
   ]},
 conversion: { title:"转换法 Conversion",
   def:"同一个词不改变拼写，由一种词类转用作另一种词类；转换后词义与原义密切相关。",
   groups:[
     {label:"名词 → 动词", items:[["water (n. 水)","to water 浇水"],["hand (n. 手)","to hand 递交"],["book (n. 书)","to book 预订"],["phone (n. 电话)","to phone 打电话"],["email (n. 邮件)","to email 发邮件"],["head (n. 头)","to head 率领"]]},
     {label:"形容词 → 动词", items:[["clean (a. 干净)","to clean 打扫"],["dry (a. 干)","to dry 弄干"],["empty (a. 空)","to empty 倒空"],["slow (a. 慢)","to slow 放慢"],["calm (a. 平静)","to calm 使平静"]]},
     {label:"动词 → 名词（多用于一次动作短语）", items:[["to swim","have a swim 游一次"],["to try","have a try 试一试"],["to walk","have a walk 散步"],["to look","have a look 看一眼"],["to rest","have a rest 休息一下"]]},
     {label:"形容词 → 名词（the + 形容词，表一类人）", items:[["the poor","穷人"],["the rich","富人"],["the young","年轻人"],["the old","老人"],["the unemployed","失业者"]]}
   ]},
 clipping: { title:"缩略法 Clipping & Abbreviation",
   def:"截取词的一部分，或取首字母拼合而成；现代英语中字母缩略尤为常见。",
   groups:[
     {label:"截尾（保留词头）", items:[["exam","← examination 考试"],["lab","← laboratory 实验室"],["photo","← photograph 照片"],["memo","← memorandum 备忘录"],["ad","← advertisement 广告"],["gym","← gymnasium 体育馆"]]},
     {label:"截头（保留词尾）", items:[["phone","← telephone 电话"],["bus","← omnibus 公共汽车"],["plane","← airplane 飞机"],["fridge","← refrigerator 冰箱"]]},
     {label:"混成词（两词拼合）", items:[["brunch","breakfast + lunch 早午餐"],["smog","smoke + fog 烟雾"],["motel","motor + hotel 汽车旅馆"],["email","electronic + mail 电邮"]]},
     {label:"首字母缩略", items:[["UN","联合国"],["CEO","首席执行官"],["DIY","自己动手"],["ASAP","尽快"],["laser","激光"],["radar","雷达"]]}
   ]},
 inflection: { title:"屈折法 Inflection",
   def:"通过改变词内部的元音或辅音构成新词，是古英语遗留的构词方式。",
   groups:[
     {label:"动词 → 名词（变元音）", items:[["sing 唱","→ song 歌曲"],["bite 咬","→ bit 一小口"],["strike 击","→ stroke 一击"]]},
     {label:"动词 → 名词（变辅音）", items:[["speak 说","→ speech 演说"],["live 生活","→ life 生命"],["choose 选","→ choice 选择"],["believe 相信","→ belief 信念"],["lose 失去","→ loss 损失"]]},
     {label:"名词 → 动词（变元音）", items:[["food 食物","→ feed 喂养"],["blood 血","→ bleed 流血"],["gold 金","→ gild 镀金"]]},
     {label:"名词 ↔ 动词（软化辅音 θ/s→ð/z）", items:[["bath 洗澡","→ bathe 沐浴"],["breath 气息","→ breathe 呼吸"],["cloth 布","→ clothe 给…穿衣"],["use [juːs]","→ use [juːz] 使用"]]}
   ]}
},

/* ===================== 同族词 ===================== */
families: [
 {root:"act", members:[["act","n./v.","行为；表演"],["action","n.","行动"],["active","a.","积极的"],["activity","n.","活动"],["actor","n.","男演员"],["actress","n.","女演员"],["actual","a.","实际的"]]},
 {root:"able", members:[["able","a.","有能力的"],["ably","ad.","能干地"],["ability","n.","能力"],["enable","v.","使能够"],["unable","a.","不能的"]]},
 {root:"care", members:[["care","n./v.","关心；小心"],["careful","a.","仔细的"],["careless","a.","粗心的"],["carefully","ad.","仔细地"],["carefree","a.","无忧的"]]},
 {root:"friend", members:[["friend","n.","朋友"],["friendly","a.","友好的"],["friendship","n.","友谊"],["friendless","a.","无友的"],["befriend","v.","友善对待"]]},
 {root:"help", members:[["help","n./v.","帮助"],["helper","n.","助手"],["helpful","a.","有帮助的"],["helpless","a.","无助的"]]},
 {root:"use", members:[["use","n./v.","使用"],["used","a.","用过的"],["useful","a.","有用的"],["useless","a.","无用的"],["user","n.","用户"],["usage","n.","用法"]]},
 {root:"nation", members:[["nation","n.","国家；民族"],["national","a.","国家的"],["nationality","n.","国籍"],["nationalize","v.","国有化"],["international","a.","国际的"]]},
 {root:"hope", members:[["hope","n./v.","希望"],["hopeful","a.","充满希望的"],["hopeless","a.","绝望的"],["hopefully","ad.","有希望地"]]},
 {root:"danger", members:[["danger","n.","危险"],["dangerous","a.","危险的"],["endanger","v.","危及"]]},
 {root:"employ", members:[["employ","v.","雇用"],["employer","n.","雇主"],["employee","n.","雇员"],["employment","n.","就业"],["unemployment","n.","失业"]]},
 {root:"history", members:[["history","n.","历史"],["historic","a.","有历史意义的"],["historical","a.","历史上的"],["historian","n.","历史学家"]]},
 {root:"science", members:[["science","n.","科学"],["scientist","n.","科学家"],["scientific","a.","科学的"]]},
 {root:"society", members:[["society","n.","社会"],["social","a.","社会的"],["socialism","n.","社会主义"],["socialist","n.","社会主义者"]]},
 {root:"produce", members:[["produce","v.","生产"],["product","n.","产品"],["production","n.","生产"],["productive","a.","多产的"],["producer","n.","生产者"]]},
 {root:"real", members:[["real","a.","真实的"],["reality","n.","现实"],["realize","v.","实现"],["really","ad.","真正地"]]},
 {root:"decide", members:[["decide","v.","决定"],["decision","n.","决定"],["decisive","a.","决定性的"]]},
 {root:"educate", members:[["educate","v.","教育"],["education","n.","教育"],["educational","a.","教育的"],["educator","n.","教育者"]]},
 {root:"economy", members:[["economy","n.","经济"],["economic","a.","经济的"],["economical","a.","节约的"],["economist","n.","经济学家"]]},
 {root:"culture", members:[["culture","n.","文化"],["cultural","a.","文化的"],["cultivate","v.","耕种；培养"],["cultivation","n.","耕种"]]},
 {root:"industry", members:[["industry","n.","工业"],["industrial","a.","工业的"],["industrious","a.","勤勉的"],["industrialize","v.","工业化"]]},
 {root:"invent", members:[["invent","v.","发明"],["invention","n.","发明"],["inventor","n.","发明家"],["inventive","a.","有创造力的"]]},
 {root:"hero", members:[["hero","n.","英雄"],["heroic","a.","英勇的"],["heroine","n.","女英雄"],["heroically","ad.","英勇地"]]},
 {root:"poem", members:[["poem","n.","诗"],["poet","n.","诗人"],["poetic","a.","诗的"],["poetry","n.","诗歌(总称)"]]},
 {root:"politics", members:[["politics","n.","政治"],["political","a.","政治的"],["politician","n.","政治家"]]},
 {root:"music", members:[["music","n.","音乐"],["musical","a.","音乐的"],["musician","n.","音乐家"]]},
 {root:"library", members:[["library","n.","图书馆"],["librarian","n.","图书管理员"]]},
 {root:"office", members:[["office","n.","办公室"],["officer","n.","官员"],["official","a./n.","官方的；官员"]]},
 {root:"family", members:[["family","n.","家庭"],["familiar","a.","熟悉的"],["familiarize","v.","使熟悉"]]},
 {root:"fail", members:[["fail","v.","失败"],["failure","n.","失败"],["failing","n.","缺点"]]},
 {root:"fertile", members:[["fertile","a.","肥沃的"],["fertility","n.","肥沃"],["fertilize","v.","施肥"],["fertilizer","n.","肥料"]]},
 {root:"memory", members:[["memory","n.","记忆"],["memorial","n.","纪念物"],["memorable","a.","难忘的"],["memorize","v.","记住"]]},
 {root:"possible", members:[["possible","a.","可能的"],["impossible","a.","不可能的"],["possibility","n.","可能性"],["possibly","ad.","可能地"]]},
 {root:"certain", members:[["certain","a.","确定的"],["certainly","ad.","当然"],["uncertain","a.","不确定的"],["certainty","n.","确定"]]},
 {root:"modern", members:[["modern","a.","现代的"],["modernize","v.","使现代化"],["modernization","n.","现代化"],["modernity","n.","现代性"]]},
 {root:"theory", members:[["theory","n.","理论"],["theoretic(al)","a.","理论的"],["theorist","n.","理论家"]],
   note:"原书印作 theoritic，正确为 theoretical。"},
 {root:"unite", members:[["unit","n.","单位"],["unite","v.","联合"],["unity","n.","统一"],["unify","v.","使统一"],["union","n.","联盟"]],
   note:"原书 unity 一行误印为 unify，此处已修正。"},
 {root:"depth", members:[["deep","a.","深的"],["deepen","v.","加深"],["depth","n.","深度"],["deeply","ad.","深深地"]]},
 {root:"strong", members:[["strong","a.","强壮的"],["strength","n.","力量"],["strengthen","v.","加强"]]},
 {root:"heal", members:[["heal","v.","治愈"],["health","n.","健康"],["healthy","a.","健康的"],["healthful","a.","有益健康的"]]},
 {root:"drama", members:[["drama","n.","戏剧"],["dramatic","a.","戏剧性的"],["dramatist","n.","剧作家"]]}
],

/* ===================== 同音异义词（音同形异）===================== */
homophones: [
 {ipa:"siː", words:[["sea","海"],["see","看见"]]},
 {ipa:"miːt", words:[["meat","肉"],["meet","遇见"]]},
 {ipa:"raɪt", words:[["right","对的；右"],["write","写"],["rite","仪式"]]},
 {ipa:"nəʊ", words:[["know","知道"],["no","不"]]},
 {ipa:"baɪ", words:[["buy","买"],["by","靠近"],["bye","再见"]]},
 {ipa:"təʊ", words:[["to","向"],["too","也"],["two","二"]]},
 {ipa:"hɪə", words:[["hear","听见"],["here","这里"]]},
 {ipa:"deə", words:[["dear","亲爱的"],["deer","鹿"]]},
 {ipa:"sʌn", words:[["son","儿子"],["sun","太阳"]]},
 {ipa:"flaʊə", words:[["flour","面粉"],["flower","花"]]},
 {ipa:"aʊə", words:[["hour","小时"],["our","我们的"]]},
 {ipa:"aɪ", words:[["eye","眼睛"],["I","我"]]},
 {ipa:"pleɪn", words:[["plain","平坦的"],["plane","飞机"]]},
 {ipa:"weɪst", words:[["waist","腰"],["waste","浪费"]]},
 {ipa:"weɪ", words:[["way","路"],["weigh","称重"]]},
 {ipa:"weɪt", words:[["wait","等待"],["weight","重量"]]},
 {ipa:"piːs", words:[["peace","和平"],["piece","一片"]]},
 {ipa:"breɪk", words:[["break","打破"],["brake","刹车"]]},
 {ipa:"feə", words:[["fair","公平的"],["fare","车费"]]},
 {ipa:"beə", words:[["bare","赤裸的"],["bear","熊；忍受"]]},
 {ipa:"peə", words:[["pear","梨"],["pair","一对"],["pare","削皮"]]},
 {ipa:"meɪl", words:[["mail","邮件"],["male","男性的"]]},
 {ipa:"seɪl", words:[["sail","航行"],["sale","出售"]]},
 {ipa:"teɪl", words:[["tail","尾巴"],["tale","故事"]]},
 {ipa:"sent", words:[["cent","分"],["sent","送(过去式)"],["scent","香味"]]},
 {ipa:"sel", words:[["cell","细胞"],["sell","卖"]]},
 {ipa:"stiːl", words:[["steal","偷"],["steel","钢"]]},
 {ipa:"hiːl", words:[["heal","治愈"],["heel","脚跟"]]},
 {ipa:"hɔːs", words:[["hoarse","嘶哑的"],["horse","马"]]},
 {ipa:"həʊl", words:[["hole","洞"],["whole","全部的"]]},
 {ipa:"sɔː", words:[["sore","疼痛的"],["soar","高飞"]]},
 {ipa:"sɔːs", words:[["sauce","酱汁"],["source","来源"]]},
 {ipa:"ɔː", words:[["oar","桨"],["or","或者"],["ore","矿石"]]},
 {ipa:"fɔː", words:[["for","为了"],["four","四"]]},
 {ipa:"red", words:[["read","读(过去式)"],["red","红色的"]]},
 {ipa:"riːd", words:[["read","读"],["reed","芦苇"]]},
 {ipa:"naɪt", words:[["knight","骑士"],["night","夜晚"]]},
 {ipa:"nɒt", words:[["knot","结"],["not","不"]]},
 {ipa:"saɪt", words:[["sight","视力"],["site","地点"],["cite","引用"]]},
 {ipa:"reɪn", words:[["rain","雨"],["reign","统治"],["rein","缰绳"]]},
 {ipa:"veɪn", words:[["vain","徒劳的"],["vein","静脉"],["vane","风向标"]]},
 {ipa:"səʊ", words:[["sew","缝"],["so","所以"],["sow","播种"]]},
 {ipa:"səʊl", words:[["sole","唯一的"],["soul","灵魂"]]},
 {ipa:"ləʊn", words:[["lone","孤独的"],["loan","贷款"]]},
 {ipa:"ðeə", words:[["their","他们的"],["there","那里"]]},
 {ipa:"wiːk", words:[["weak","虚弱的"],["week","星期"]]},
 {ipa:"wud", words:[["wood","木头"],["would","将会"]]},
 {ipa:"sʌm", words:[["some","一些"],["sum","总和"]]},
 {ipa:"greɪt", words:[["great","伟大的"],["grate","磨碎"]]},
 {ipa:"hɔːl", words:[["hall","大厅"],["haul","拖拽"]]},
 {ipa:"biː", words:[["be","是"],["bee","蜜蜂"]]},
 {ipa:"daɪ", words:[["die","死"],["dye","染色"]]},
 {ipa:"prɪnsɪpl", words:[["principal","校长；主要的"],["principle","原则"]]},
 {ipa:"ˈpræktɪs", words:[["practice","练习(名词)"],["practise","练习(动词)"]]},
 {ipa:"eə", words:[["air","空气"],["heir","继承人"]]},
 {ipa:"θruː", words:[["through","通过"],["threw","扔(过去式)"]]},
 {ipa:"flɔː", words:[["floor","地板"],["flaw","瑕疵"]]}
],

/* ===================== 一词多义（同形同音多义）===================== */
polysemy: [
 {w:"arm", senses:[["n.","手臂"],["n.","武器(arms)"],["v.","武装"]]},
 {w:"bank", senses:[["n.","河岸"],["n.","银行"]]},
 {w:"bark", senses:[["n.","狗叫"],["n.","树皮"]]},
 {w:"bear", senses:[["n.","熊"],["v.","忍受；生育"]]},
 {w:"book", senses:[["n.","书"],["v.","预订"]]},
 {w:"box", senses:[["n.","箱子"],["v.","拳击"]]},
 {w:"can", senses:[["aux.","能够"],["n.","罐头"]]},
 {w:"case", senses:[["n.","箱子"],["n.","情况；案件"]]},
 {w:"company", senses:[["n.","公司"],["n.","陪伴"]]},
 {w:"date", senses:[["n.","日期"],["n.","约会"],["n.","枣"]]},
 {w:"fair", senses:[["a.","公平的；美丽的"],["n.","集市；展览会"]]},
 {w:"fan", senses:[["n.","扇子"],["n.","粉丝"]]},
 {w:"fine", senses:[["a.","好的；精细的"],["n.","罚款"]]},
 {w:"firm", senses:[["a.","坚固的"],["n.","公司"]]},
 {w:"kind", senses:[["a.","友善的"],["n.","种类"]]},
 {w:"last", senses:[["a.","最后的"],["v.","持续"]]},
 {w:"left", senses:[["a./n.","左"],["v.","leave 的过去式"]]},
 {w:"light", senses:[["n.","光"],["a.","轻的；明亮的"]]},
 {w:"like", senses:[["v.","喜欢"],["prep.","像"]]},
 {w:"long", senses:[["a.","长的"],["v.","渴望"]]},
 {w:"match", senses:[["n.","火柴"],["n.","比赛"],["v.","匹配"]]},
 {w:"mean", senses:[["v.","意味着"],["a.","卑鄙的；吝啬的"]]},
 {w:"mine", senses:[["pron.","我的"],["n.","矿"]]},
 {w:"miss", senses:[["n.","小姐"],["v.","错过；想念"]]},
 {w:"net", senses:[["n.","网"],["a.","净的"]]},
 {w:"page", senses:[["n.","页"],["n.","男侍童"]]},
 {w:"park", senses:[["n.","公园"],["v.","停车"]]},
 {w:"pen", senses:[["n.","钢笔"],["n.","围栏"]]},
 {w:"pole", senses:[["n.","杆子"],["n.","极地"]]},
 {w:"present", senses:[["a.","出席的；现在的"],["n.","礼物"],["v.","呈现"]]},
 {w:"race", senses:[["n.","赛跑"],["n.","种族"]]},
 {w:"rest", senses:[["n.","休息"],["n.","其余"]]},
 {w:"ring", senses:[["n.","戒指"],["v.","响铃"]]},
 {w:"rock", senses:[["n.","岩石"],["v.","摇动"],["n.","摇滚乐"]]},
 {w:"row", senses:[["n.","一排"],["v.","划船"]]},
 {w:"save", senses:[["v.","拯救；节省"],["prep.","除……之外"]]},
 {w:"sound", senses:[["n.","声音"],["a.","健全的"]]},
 {w:"spring", senses:[["n.","春天"],["n.","弹簧"],["v.","跳跃"]]},
 {w:"stick", senses:[["n.","棍子"],["v.","粘住"]]},
 {w:"tip", senses:[["n.","尖端"],["n.","小费"],["n.","提示"]]},
 {w:"watch", senses:[["n.","手表"],["v.","观看"]]},
 {w:"well", senses:[["ad.","好"],["n.","井"]]},
 {w:"yard", senses:[["n.","码(长度)"],["n.","院子"]]}
],

/* ===================== 同形异音异义（重音/读音变化）===================== */
heteronyms: [
 {w:"record", readings:[["ˈrekɔːd","n.","记录；唱片"],["rɪˈkɔːd","v.","记录；录音"]]},
 {w:"present", readings:[["ˈpreznt","n./a.","礼物；现在的"],["prɪˈzent","v.","呈现；颁发"]]},
 {w:"object", readings:[["ˈɒbdʒɪkt","n.","物体；宾语"],["əbˈdʒekt","v.","反对"]]},
 {w:"subject", readings:[["ˈsʌbdʒɪkt","n.","主题；学科"],["səbˈdʒekt","v.","使服从"]]},
 {w:"desert", readings:[["ˈdezət","n.","沙漠"],["dɪˈzɜːt","v.","抛弃；开小差"]]},
 {w:"content", readings:[["ˈkɒntent","n.","内容"],["kənˈtent","a.","满足的"]]},
 {w:"contrast", readings:[["ˈkɒntrɑːst","n.","对比"],["kənˈtrɑːst","v.","对照"]]},
 {w:"increase", readings:[["ˈɪnkriːs","n.","增加(量)"],["ɪnˈkriːs","v.","增加"]]},
 {w:"export", readings:[["ˈekspɔːt","n.","出口(品)"],["ɪkˈspɔːt","v.","出口"]]},
 {w:"import", readings:[["ˈɪmpɔːt","n.","进口(品)"],["ɪmˈpɔːt","v.","进口"]]},
 {w:"rebel", readings:[["ˈrebl","n.","反叛者"],["rɪˈbel","v.","反抗"]]},
 {w:"refuse", readings:[["ˈrefjuːs","n.","废物"],["rɪˈfjuːz","v.","拒绝"]]},
 {w:"accent", readings:[["ˈæksent","n.","口音；重音"],["əkˈsent","v.","强调"]]},
 {w:"conduct", readings:[["ˈkɒndʌkt","n.","行为"],["kənˈdʌkt","v.","进行；指挥"]]},
 {w:"bow", readings:[["baʊ","v.","鞠躬"],["bəʊ","n.","弓；蝴蝶结"]]},
 {w:"lead", readings:[["liːd","v.","领导"],["led","n.","铅"]]},
 {w:"tear", readings:[["tɪə","n.","眼泪"],["teə","v.","撕裂"]]},
 {w:"wind", readings:[["wɪnd","n.","风"],["waɪnd","v.","蜿蜒；上发条"]]},
 {w:"live", readings:[["lɪv","v.","居住；生活"],["laɪv","a.","现场的；活的"]]},
 {w:"close", readings:[["kləʊz","v.","关闭"],["kləʊs","a.","近的"]]},
 {w:"use", readings:[["juːz","v.","使用"],["juːs","n.","用途"]]},
 {w:"minute", readings:[["ˈmɪnɪt","n.","分钟"],["maɪˈnjuːt","a.","微小的"]]},
 {w:"wound", readings:[["wuːnd","n.","伤口"],["waʊnd","v.","wind 的过去式"]]}
],

/* ===================== 同义词（含用法辨析）===================== */
synonyms: [
 {cat:"形容词", note:"“大”的三兄弟", group:[["big","大（体积/数量，口语常用）"],["large","大（面积/规模，较正式）"],["great","大；伟大（程度/抽象/赞叹）"]]},
 {cat:"形容词", note:"小", group:[["little","小（常含感情色彩，可爱/可怜）"],["small","小（客观尺寸，中性）"]]},
 {cat:"形容词", note:"好", group:[["good","好（最通用）"],["fine","好；精致"],["nice","好；宜人"],["excellent","极好"]]},
 {cat:"形容词", note:"高", group:[["tall","高（人/树等细长物）"],["high","高（高度/地势/抽象）"]]},
 {cat:"形容词", note:"病", group:[["ill","生病的（多作表语）"],["sick","生病的；恶心的（可作定语）"]]},
 {cat:"形容词", note:"安静", group:[["quiet","安静（无吵闹）"],["calm","平静（无波动/镇定）"],["silent","沉默（不出声）"],["still","静止（不动）"]]},
 {cat:"形容词", note:"干净/整洁", group:[["clean","干净（无污垢）"],["tidy","整洁（有条理）"],["neat","整齐（简洁利落）"]]},
 {cat:"形容词", note:"美", group:[["beautiful","美丽（通用，程度高）"],["pretty","漂亮（小巧可爱）"],["handsome","英俊（多指男性）"],["lovely","可爱（带感情）"]]},
 {cat:"形容词", note:"能", group:[["able","能（be able to do）"],["capable","有能力（be capable of doing）"]]},
 {cat:"形容词", note:"清楚", group:[["clear","清晰；明白"],["plain","浅显；朴素"],["distinct","清楚；明显"]]},
 {cat:"形容词", note:"快", group:[["quick","快（动作敏捷）"],["fast","快（速度高，可作副词）"]]},
 {cat:"名词", note:"力量", group:[["force","力；武力"],["strength","力气；强度"],["power","权力；动力"],["might","威力（书面）"]]},
 {cat:"名词", note:"工作", group:[["work","工作（总称，不可数）"],["job","工作（一份职位，可数）"],["task","任务（具体的）"]]},
 {cat:"名词", note:"机会", group:[["chance","机会（偶然）"],["opportunity","机会（有利时机）"]]},
 {cat:"名词", note:"医生", group:[["doctor","医生（通称）"],["physician","内科医生"],["surgeon","外科医生"]]},
 {cat:"名词", note:"土地", group:[["land","陆地；土地"],["ground","地面"],["soil","土壤"],["earth","泥土；地球"]]},
 {cat:"名词", note:"自由", group:[["freedom","自由（强调个人）"],["liberty","自由（权利，多指集体）"]]},
 {cat:"名词", note:"敌人", group:[["enemy","敌人（通用）"],["foe","仇敌（书面/诗歌）"]]},
 {cat:"名词", note:"会议", group:[["meeting","会议（一般）"],["conference","正式大会"],["rally","群众集会"],["congress","代表大会"]]},
 {cat:"名词", note:"路", group:[["road","公路；道路"],["way","路；方式"],["path","小径"],["street","街道"]]},
 {cat:"名词", note:"海", group:[["sea","海"],["ocean","大洋"]]},
 {cat:"动词", note:"看", group:[["see","看见（结果）"],["look","看（动作，look at）"],["watch","注视；观看（持续）"]]},
 {cat:"动词", note:"说", group:[["say","说（强调内容）"],["speak","说（强调动作/语言）"],["talk","交谈"],["tell","告诉（某人某事）"]]},
 {cat:"动词", note:"问/答", group:[["ask","问"],["inquire","询问（正式）"],["answer","回答"],["reply","答复"]]},
 {cat:"动词", note:"忍受", group:[["bear","忍受"],["stand","忍受（多用于否定）"],["endure","忍耐（长期）"]]},
 {cat:"动词", note:"开始", group:[["begin","开始（通用）"],["start","开始；出发；启动"]]},
 {cat:"动词", note:"建造", group:[["build","建造"],["construct","建造（大型/正式）"],["erect","竖立"]]},
 {cat:"动词", note:"帮助", group:[["help","帮助（通用）"],["assist","协助"],["aid","援助（正式）"]]},
 {cat:"动词", note:"想要", group:[["want","想要（直接）"],["wish","希望（较正式/不易实现）"],["desire","渴望（强烈/正式）"],["long","渴望（long for）"]]},
 {cat:"动词", note:"哭", group:[["cry","哭；喊"],["weep","流泪（书面）"],["sob","抽泣"]]},
 {cat:"动词", note:"笑", group:[["laugh","大笑"],["smile","微笑"],["grin","咧嘴笑"],["chuckle","轻声笑"]]},
 {cat:"动词", note:"穿", group:[["wear","穿着（状态）"],["put on","穿上（动作）"]]},
 {cat:"动词", note:"选择", group:[["choose","选择（通用）"],["select","精选"]]},
 {cat:"副词", note:"也", group:[["also","也（较正式，居中）"],["too","也（口语，句末）"],["as well","也（句末）"]]},
 {cat:"副词", note:"几乎", group:[["almost","几乎"],["nearly","将近"]]},
 {cat:"副词", note:"也许", group:[["perhaps","也许（较正式）"],["maybe","也许（口语）"],["probably","很可能"]]},
 {cat:"连词", note:"因为", group:[["because","因为（语气最强，答 why）"],["since","既然"],["as","由于"],["for","因为（书面，补充原因）"]]},
 {cat:"介词", note:"在……下", group:[["under","在……正下方"],["below","在……下方（不一定正下）"],["beneath","在……下（书面/紧贴）"]]}
],

/* ===================== 反义词 ===================== */
antonyms: [
 {cat:"动词", a:["ask","问"], b:["answer","答"]},
 {cat:"动词", a:["arrive","到达"], b:["depart","离开"]},
 {cat:"动词", a:["begin","开始"], b:["end","结束"]},
 {cat:"动词", a:["buy","买"], b:["sell","卖"]},
 {cat:"动词", a:["open","打开"], b:["close","关闭"]},
 {cat:"动词", a:["borrow","借入"], b:["lend","借出"]},
 {cat:"动词", a:["accept","接受"], b:["refuse","拒绝"]},
 {cat:"动词", a:["appear","出现"], b:["disappear","消失"]},
 {cat:"动词", a:["lead","领导"], b:["follow","跟随"]},
 {cat:"动词", a:["come","来"], b:["go","去"]},
 {cat:"动词", a:["enter","进入"], b:["leave","离开"]},
 {cat:"动词", a:["live","生存"], b:["die","死亡"]},
 {cat:"动词", a:["win","获胜"], b:["lose","失败"]},
 {cat:"动词", a:["love","爱"], b:["hate","恨"]},
 {cat:"动词", a:["remember","记得"], b:["forget","忘记"]},
 {cat:"动词", a:["rise","上升"], b:["fall","下降"]},
 {cat:"动词", a:["push","推"], b:["pull","拉"]},
 {cat:"动词", a:["teach","教"], b:["learn","学"]},
 {cat:"形容词", a:["big","大的"], b:["small","小的"]},
 {cat:"形容词", a:["long","长的"], b:["short","短的"]},
 {cat:"形容词", a:["high","高的"], b:["low","低的"]},
 {cat:"形容词", a:["deep","深的"], b:["shallow","浅的"]},
 {cat:"形容词", a:["wide","宽的"], b:["narrow","窄的"]},
 {cat:"形容词", a:["thick","厚的"], b:["thin","薄的"]},
 {cat:"形容词", a:["heavy","重的"], b:["light","轻的"]},
 {cat:"形容词", a:["strong","强的"], b:["weak","弱的"]},
 {cat:"形容词", a:["hard","硬的"], b:["soft","软的"]},
 {cat:"形容词", a:["hot","热的"], b:["cold","冷的"]},
 {cat:"形容词", a:["dry","干的"], b:["wet","湿的"]},
 {cat:"形容词", a:["black","黑的"], b:["white","白的"]},
 {cat:"形容词", a:["bright","明亮的"], b:["dark","黑暗的"]},
 {cat:"形容词", a:["clean","干净的"], b:["dirty","脏的"]},
 {cat:"形容词", a:["good","好的"], b:["bad","坏的"]},
 {cat:"形容词", a:["right","对的"], b:["wrong","错的"]},
 {cat:"形容词", a:["easy","容易的"], b:["difficult","困难的"]},
 {cat:"形容词", a:["fast","快的"], b:["slow","慢的"]},
 {cat:"形容词", a:["new","新的"], b:["old","旧的"]},
 {cat:"形容词", a:["young","年轻的"], b:["old","年老的"]},
 {cat:"形容词", a:["rich","富的"], b:["poor","穷的"]},
 {cat:"形容词", a:["happy","快乐的"], b:["sad","悲伤的"]},
 {cat:"形容词", a:["full","满的"], b:["empty","空的"]},
 {cat:"形容词", a:["same","相同的"], b:["different","不同的"]},
 {cat:"形容词", a:["early","早的"], b:["late","晚的"]},
 {cat:"形容词", a:["first","最初的"], b:["last","最后的"]},
 {cat:"名词", a:["day","白天"], b:["night","夜晚"]},
 {cat:"名词", a:["sky","天空"], b:["earth","大地"]},
 {cat:"名词", a:["front","前面"], b:["back","后面"]},
 {cat:"名词", a:["man","男人"], b:["woman","女人"]},
 {cat:"名词", a:["question","问题"], b:["answer","回答"]},
 {cat:"名词", a:["friend","朋友"], b:["enemy","敌人"]},
 {cat:"名词", a:["beginning","开始"], b:["end","结束"]},
 {cat:"名词", a:["cause","原因"], b:["effect","结果"]}
]
};
